version: "3"
services:
  nimble-redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server

  nimble-client:
    build:
      dockerfile: Dockerfile.dev
      context: ../Nimble-client
    volumes:
      - /app/node_modules
      - ../Nimble-client:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true

  nimble-nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  nimble-server:
    build:
      dockerfile: Dockerfile.dev
      context: ../Nimble-server
    volumes:
      - /app/node_modules
      - ../Nimble-server:/usr/src/app
    ports:
      - "3001:3001"
